name = "EvalMetrics"
uuid = "251d5f9e-10c1-4699-ba24-e0ad168fa3e4"
authors = ["Vaclav Macha <vaclav.macha92@gmail.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "^1.0"
